# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest
    container: rubentgx/dotnetcoverageprinter:v1.0.0 # your docker image
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: /app/scripts/print-dotnet-coverage.sh Cobertura.xml
